# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default=('Feature', 'Feature'), max_length=50)),
                ('description', models.TextField()),
                ('views', models.BigIntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
