# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190530_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
