# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_bug_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='issue_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default=('Feature', 'Feature'), max_length=50),
        ),
        migrations.AddField(
            model_name='bug',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bug',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bug',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
