# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20190623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='ticket_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In progress', 'In Progress'), ('Complete', 'Complete')], default=('Waiting', 'Waiting'), max_length=50),
        ),
    ]
