# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_auto_20190623_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='ticket_status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Doing', 'Doing'), ('Done', 'Done')], default=('Todo', 'Todo'), max_length=50),
        ),
    ]
