# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_auto_20190623_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='issue_type',
            field=models.CharField(default='Feature', max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='ticket_status',
            field=models.CharField(default='Todo', max_length=50),
        ),
    ]
