# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0013_auto_20190630_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Bug',
        ),
    ]
